### ISSUE TITLE
Status bar for "DRAFT" seems to have a strange color

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#107]
From #106 the screenshot seems to show the status bar missing background color.

<img width="412" alt="Screen Shot 2020-03-10 at 8 11 53 AM" src="https://user-images.githubusercontent.com/11865/76267775-ceb0ae00-62a6-11ea-90c1-890f597f9323.png">

**Comment by opoudjis** [comment]
Two issues:

* `id='{{ stage | downcase | replace " ", "-" }}-band'` was not working, who knows why, `id='{{ stage | downcase | replace ' ', '-' }}-band'` works. Globally replace in all bands.
* Because id was falsely getting the value "swg draft-band", no colour was being allocated to the stage band, and that was ending up with it being translucent. Set up default background in isodoc base class for stage bands that don't have a value accounted for in the stylesheet.

I've updated the stages and document types in the HTML stylesheet against the known values for OGC.

**Comment by opoudjis** [comment]
Added fallback of white background for bands with no recognised value.

**Comment by ronaldtse** [comment]
Wait- white background with white text?

**Comment by opoudjis** [comment]
... Oh. OK, will change to Black background
