### ISSUE TITLE
Proper markup for Conformance Class + Abstract Test?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#110]
From @manuel489:

> I stumbled with a problem: this document contains *Conformance Class* and *Abstract Test* blocks. And I believe we don't have a proper markup for these cases. (I didn't find any documentation about it.)

To give an example of these two blocks:

*Conformance Class:*
![capture-conformance](https://user-images.githubusercontent.com/33627611/76543637-2db82380-645d-11ea-8337-3e2da2283866.PNG)

*Abstract Test:*
![capture-abstract](https://user-images.githubusercontent.com/33627611/76543783-5f30ef00-645d-11ea-9597-95e2b531e3df.PNG)

Ping @opoudjis 

Thanks!

_Originally posted by @manuel489 in https://github.com/metanorma/mn-samples-ogc/pull/57#issuecomment-598286023_

**Comment by opoudjis** [comment]
The model we have from OGC to date, which drives the idiosyncratic formatting they require of requirements is:

* Requirement
* `Requirement[@type = "class"]`: superset of Requirement
* `Requirement[@type = "verification"]` validation of Requirement

Each is rendered and referenced in a different way.

We cannot implement novel types of requirement without specification of expected behaviour.

I'm finding https://github.com/opengeospatial/ogcapi-features/issues/301 difficult to navigate, but I will (for now) treat:

* Conformance Class as a parallel to Requirement Class, rendered the same way, but referenced as a distinct sequence. They will be marked up as `type=conformanceclass`.
* Abstract Test as a parallel to Requirement Verifications, rendered the same way, but referenced as a distinct sequence. They will be marked up as `type=abstracttest`.

We would welcome a more formal description from OGC of the classes at play. "Requirement" for these purposes ends up being "anything that gets marked up in the tabular format provided.
