### ISSUE TITLE
Double rendering of the "OGC" in "OGC OGC 11-145" in references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#129]
https://metanorma.github.io/mn-samples-ogc/documents/18-053r2.html#toc8

<img width="767" alt="image" src="https://user-images.githubusercontent.com/11865/78060956-05b64300-73bf-11ea-9cc6-2fb2da4b3b7b.png">

**Comment by opoudjis** [comment]
Two issues.

Second issue, the expectation is the docidentifier in the record returned by relaton-ogc does not contain "OGC" at the start; metanorma inserts the OGC prefix. However, in this case, the relaton-ogc does contain the prefix, so OGC is added redundantly.

But that is irrelevant, because the citation is mangled: the document identifier given is just "OGC", which means that the reference retrieved is random. The intended citation is OGC 12-063r5, and it's retrieving OGC 11-145.

I mean, who thought that this made sense as a Metanorma citation?

````
* [[[OGC,OGC]]], OGC: [OGC 12-063r5] Geographic information - Well-known text representation of coordinate reference systems, 2015. http://docs.opengeospatial.org/is/12-063r5/12-063r5.html[http://docs.opengeospatial.org/is/12-063r5/12-063r5.html]
````

Fixing this to the correct

````
* [[[OGC,OGC 12-063r5]]], OGC: [OGC 12-063r5] Geographic information - Well-known text representation of coordinate reference systems, 2015. http://docs.opengeospatial.org/is/12-063r5/12-063r5.html[http://docs.opengeospatial.org/is/12-063r5/12-063r5.html]
````

is processed correctly as

> [1]  Open Geospatial Consortium: OGC 12-063r5, Geographic information — Well known text representation of coordinate reference systems. Open Geospatial Consortium (2015).

Please fix in source document, and do some sort of QA before passing non-bugs onto me.
