### ISSUE TITLE
Missing "requirement class" requirement number in HTML output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#150]
From @ghobona :

> I could not find a way to display the Requirement number in the Requirement Class. So currently the only way to link a Requirements Class to the Requirements within it is through the URI (/req/...).

> Is there a way to enable the Requirement number to appear on the Requirements Class in which it belongs?

![](https://user-images.githubusercontent.com/18121038/83853480-3f802e80-a70d-11ea-8396-af232761af27.png)

Tracked at https://github.com/opengeospatial/ogc-metanorma-testing/issues/24#event-3410213358

**Comment by opoudjis** [comment]
"Requirement 1" is a cross-reference, it is a dynamic property of a document and not static. If a new requirement is interpolated, it becomes requirement 1. If the number needs to remain static, it needs to become a property of the requirement.

Since it is a cross-reference, the way to insert it is as a cross-reference. But since there already is a cross-reference, in the form of the label, the simplest thing to do here is to inject a cross-reference to a downstream requirement, whenever a nested requirement has the same label as an un-nested requirement.

However, it is difficult to implement these rules on an ad hoc basis. (And as we've discussed, it's become prohibitive for PDF generation.) Is there documentation of how requirements cross-reference requirements that we can work from?

**Comment by opoudjis** [comment]
Implemented as:

````
| Requirement     | Requirement 1, /req/conceptual/similarity
````

The rule applied is as mentioned above; in more detail:

* All requirements &c are labelled in the first row as Requirement/Requirement Class NUMBER, optionally followed by title
* All requirements have the label in the second row
* All nested requirements are rendered by transforming their first and second row into first and second cells on the same row
** So we would get `| Requirement NUMBER: Title | label `
* But we do the following additional manipulations on an embedded requirement, because we know it will be cross referenced:
** We label it just "Requirement" (or Requirement Class), no number and no title
** Before the label, we inject a crossreference to the top level requirement with the same label
** So we get instead `| Requirement | Requirement NUMBER_2, label `

**Comment by opoudjis** [comment]
I'm seeing from https://github.com/opengeospatial/templates/blob/master/standard_template/standard/requirements/requirements_class.adoc that there is an expectation of the label being on the left hand side of the table. Reopening.
