### ISSUE TITLE
Document attribute for setting one or more copyright holders

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#158]
Requested by @ghobona.

> In most cases (more than 90% of cases) the copyright owner will be Open Geospatial Consortium.
> There should be a document property for setting the copyright owner.

We need to have a mechanism for specifying copyright owner, potentially more than one.

Originally from https://github.com/metanorma/metanorma-ogc/issues/157

**Comment by opoudjis** [comment]
Will be standoc-level attribute

**Comment by ronaldtse** [comment]
I trust you mean "attributes" :wink:

**Comment by ronaldtse** [comment]
From @ghobona:

In some cases (e.g. 3D Tiles) the copyright is jointly owned by Cesium and OGC.

![](https://user-images.githubusercontent.com/18121038/85989332-489cac80-b9e8-11ea-9f44-c5ad6a79aee3.png)

We will need to model the copyright holders properly.

**Comment by opoudjis** [comment]
The rule shall be:

On data entry, the copyright holder shall be the document attribute "copyright-holder" if present. If not, it shall be the document attribute "publisher" if present. Copyright holders can be comma-delimited.

Output uses whichever contributors are tagged as copyright holders. That won't change; but the input is being changed to decouple copyright holders and publishers.

I'm switching from naive split to CSV split on comma, so that quotations can be used; e.g. `copyright-holder: "Ribose, Inc.", Open Geospatial Consortium`

**Comment by opoudjis** [comment]
Also refactoring all flavours, to remove repetitions of publisher and copyright processing, replacing them with a call to default_publisher()
