### ISSUE TITLE
DOC vs PDF: Example title alignment

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#165]
Example title is center-aligned in DOC, and left-aligned in PDF. 

DOC:
![issue7-doc](https://user-images.githubusercontent.com/33627611/86544483-490bda80-bef5-11ea-90e4-a0ef96846366.PNG)

PDF;
![issue7-pdf](https://user-images.githubusercontent.com/33627611/86544486-50cb7f00-bef5-11ea-83a1-fb1de0f90533.PNG)

Which one is correct?

**Comment by Intelligent2013** [comment]
Fixed in XSLT:
![изображение](https://user-images.githubusercontent.com/5559926/86934651-9e89f680-c144-11ea-9124-56e286fb21f0.png)

**Comment by opoudjis** [comment]
Well, actually, the PDFs I'm seeing left align captions, because it just duplicates out-of-the-box Asciidoctor HTML formatting. To my slight surprise, I have merged example captions with sourcecode labels in OGC specifically, and I must have had a reason for that. OGC have not raised an issue with centering in their extensive reviews, so I'll take this as OK until told otherwise.
