### ISSUE TITLE
Support for rich text in Requirement label attribute 

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#266]
Currently, label block attribute is rendering only in plain text.

Taken from [metanorma.org](https://www.metanorma.org/author/ogc/topics/requirements/):

````
[requirement,type="class",label="http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules[*req/core*]",obligation="requirement",subject="Encoding of logical models",inherit="urn:iso:dis:iso:19156:clause:7.2.2;urn:iso:dis:iso:19156:clause:8;http://www.opengis.net/doc/IS/GML/3.2/clause/2.4;O&M Abstract model, OGC 10-004r3, clause D.3.4;http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used"]
.GWML2 core logical model
====

[requirement,type="general",label="/req/core/encoding"]
======
======

[requirement,type="general",label="/req/core/quantities-uom"]
======
======
====
````

renders

![cap1](https://user-images.githubusercontent.com/33627611/131893214-363d8474-4e84-4da8-ac5c-f7be0b000a85.PNG)

Here, label text was expected to show *req/core* in bold, but it renders in plain text instead.

**Comment by manuel489** [comment]
In addition, how can I encode the *Requirement 1-1* and *Requirement 1-2* fields in DL syntax?

**Comment by ronaldtse** [comment]
> In addition, how can I encode the _Requirement 1-1_ and _Requirement 1-2_ fields in DL syntax?

@manuel489 exactly -- same question that I have. I wonder if we can mix DL syntax and the block syntax because rich text is a lot more easy to enter in block syntax. (ping @opoudjis )

Also, I am not convinced that the `label` should be rich text, because in printed form the `label` `href` is not accessible.

**Comment by ronaldtse** [comment]
@ogcscotts @gbuehler @ghobona : Could we have a clarification on the structure of the "ModSpec Label" -- should it support rich text, or just plain text?

ModSpec itself does not provide an answer, it says:
> "Each requirement may be separately identifiable either by a label as is done in this document, by its subclause number, or by its subclause number and full text."

In ModSpec itself, each requirement is only labeled by the Requirement number.
<img width="520" alt="Screenshot 2021-09-03 at 7 29 03 AM" src="https://user-images.githubusercontent.com/11865/131928629-db50d947-c72a-4589-a45d-6527fc8ca84c.png">

Since OGC now uses URIs for requirement labels, additional clarity on the practice will be helpful for authors. Thanks!

**Comment by ogcscotts** [comment]
@ronaldtse I am not sure why we would need rich text - do I follow the Issue correctly that rich text is only needed to make the text bold?

**Comment by ronaldtse** [comment]
The reason for asking is that we have seen requirements that embed a link as a label. 

For example “/req/xxx” but underneath it is a link to http://www.opengis.net/req/xxx. 

For this case it might be better to separate encoding the base path and label.

**Comment by opoudjis** [comment]
@manuel489 as a general solution: block attribute syntax should be treated as plaintext; if you want formatting, switch to definition list syntax, which will treat the attributes as general Asciidoctor text. Injecting formatting into block attributes is too much of a hassle to be worthwhile, when the alternate syntax is available. I'll note it in documentation.

**Comment by opoudjis** [comment]
> In addition, how can I encode the _Requirement 1-1_ and _Requirement 1-2_ fields in DL syntax?

I've just implemented this: you can do:

````
[%metadata]
requirement:: /req/core/encoding
````

and that will be interpreted as equivalent to:

````
[requirement,type="general",label="/req/core/encoding"]
======
======
````

**Comment by opoudjis** [comment]
In my opinion I've fulfilled this ticket, but this awaits confirmation from OGC as to whether label can be rich text.

**Comment by ghobona** [comment]
@opoudjis Please render the requirement label only as plain text.

**Comment by ronaldtse** [comment]
Thank you @ghobona for the confirmation!
