### ISSUE TITLE
Revision History appendix clause tagged as "Normative"

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#320]
Revision History appendix is being tagged as "Normative". Is that correct? (it has no tag in original source.)

```adoc
[appendix]
== Revision History
```

renders
![capture1](https://user-images.githubusercontent.com/33627611/143524934-b6bb9f7d-d9f7-44eb-ad06-bd7110d4779c.PNG)

**Comment by ronaldtse** [comment]
@manuel489 that's incorrect, Revision History is informative. However, I don't think Revision History is a mandatory section and it may not be recognised by Metanorma by default.

I think the real problem is that Metanorma OGC should by default treat all Annexes as "Informative". This was the previous behavior I'm not sure if it is only OGC that is ignoring this, or it is now wrong for all flavors.

@manuel489 could you help check? Thanks.

**Comment by manuel489** [comment]
> I think the real problem is that Metanorma OGC should by default treat all Annexes as "Informative". This was the previous behavior I'm not sure if it is only OGC that is ignoring this, or it is now wrong for all flavors.

@ronaldtse, no. Metanorma OGC treats Annexes as "Normative" by default. I have checked that out.
And, it is documented in [Annexes](https://www.metanorma.org/author/topics/document-format/sections/#annexes):

![capture2](https://user-images.githubusercontent.com/33627611/143530243-2b0f5530-203b-42e6-8ab8-dd657b8a352a.PNG)

**Comment by ronaldtse** [comment]
We probably should change this behavior. For example, the OGC Glossary section, located in the Annex, is already informative.

**Comment by manuel489** [comment]
Ok, in the mean time, I'll fix it in markup.

**Comment by ronaldtse** [comment]
Thanks @manuel489 !
