### ISSUE TITLE
PDF: Overflowing revision history table to the right

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#351]
<img width="663" alt="Screenshot 2022-01-17 at 2 09 27 AM" src="https://user-images.githubusercontent.com/11865/149672260-1f8500e8-0f5f-45d6-88f6-88ac1b85916a.png">

Document: https://github.com/metanorma/ogc-citygml2

**Comment by ronaldtse** [comment]
Can't upload XML since it's too large...

**Comment by Intelligent2013** [comment]
@ronaldtse  some tables are wide. For instance `width=754`:
from ak-revision_history.adoc :
```adoc
[[annex_k]]
[appendix,obligation="informative"]
== Revision history

[width=754,options="unnumbered"]
|===
```

Effective width of page for OGC documents is: 215.9mm (8.5in) - (left margin 35mm + right margin 17mm) = 163.9mm (6.45in).

Table width is 754px.
Resolution is 96dpi.
754 / 96 = 7.85in - this is real width of the table. I.e. overflow size is 7.85-6.45=1.4in (35.5mm)

I.e. maximum size for table  is: 6.45 * 96 = 619px.
For
```adoc
[width=619,options="unnumbered"]
|===
```

rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/149676132-b8a35d55-052c-48b1-a658-9321150890f1.png)


But, the page's right margin is 17mm, and I think we can decrease it for table up to 10mm, and then maximum width for table will be 646px.

For
```adoc
[width=646,options="unnumbered"]
|===
```
rendered pdf:
![image](https://user-images.githubusercontent.com/5559926/149676200-e6254132-5d06-4489-b321-ff9dcbc6ffec.png)

**Comment by Intelligent2013** [comment]
Except Revision History table, there are another wide tables, for instance Table 1, Table 2:
```adoc
[[tab_1]]
.List of CityGML modules, their associated XML namespace identifiers, and example namespace prefixes.
[width=774]
...
[[tab_2]]
.List of XML Schema definitions, their associated XML namespace identifiers, and example namespace prefixes used within this document.
[width=774]
|===
...
```
![image](https://user-images.githubusercontent.com/5559926/149676286-ea568766-191e-4548-aeb8-fae86c6816f9.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 What is the best way to handle this overflowing table? Can we create a warning for overflowing tables?

**Comment by Intelligent2013** [comment]
@ronaldtse I think the best way is showing a warning. No need to auto-adjust the table width to page width without left/right margins, because user may set the table width a bit wider to fill page left/right margins specially. Currently, mn2pdf shows this message in the log:
```
...
An fo:table  (See position 24595:256) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
...
```
But it looks not useful, because it points to intermediate XSL-FO, but not source table id. So, mn2pdf should be updated:
- All significant warnings (currently, all of them are warning about fonts) should be displayed at the end of log;
- the warning `An fo:table  .... is wider than the available room` should be transformed to something `A fo:table  `@id=...` .... is wider than the available width of page. Please check this overflowing table`.
I'll create a ticket for mn2pdf.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
