### ISSUE TITLE
(URGENT) PDF: Document subtype missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#387]
In https://github.com/metanorma/ogc-modspec/pull/3 this document is a "conceptual model standard" with doctype `standard` and docsubtype `conceptual model`.

According to the original PDF design, the subtype is supposed to show if it is provided.

NOTE: Please ignore the different treatment of the document attributes at the bottom. @Intelligent2013 let's discuss any differences between the implementation we have and this sample. Thanks!

<img width="611" alt="Screenshot 2022-06-15 at 9 33 14 AM" src="https://user-images.githubusercontent.com/11865/173711751-ac4f53a1-4db3-4b9d-a519-cd2c7e4d6ad6.png">

**Comment by Intelligent2013** [comment]
In xslt there is a mapping table between the value in `docsubtype` and dispayed text:
```xml
<xsl:variable name="docsubtype" select="normalize-space(/ogc:ogc-standard/ogc:bibdata/ogc:ext/ogc:docsubtype)"/>
<xsl:variable name="docsubtype_str">
	<xsl:choose>
		<xsl:when test="$docsubtype = 'implementation'">Implementation</xsl:when>
		<xsl:when test="$docsubtype = 'conceptual-model'">Conceptual model</xsl:when>
		<xsl:when test="$docsubtype = 'conceptual-model-and-encoding'">Conceptual model &amp; encoding</xsl:when>
		<xsl:when test="$docsubtype = 'conceptual-model-and-implementation'">Conceptual model &amp; implementation</xsl:when>
		<xsl:when test="$docsubtype = 'encoding'">Encoding</xsl:when>
		<xsl:when test="$docsubtype = 'extension'">Extension</xsl:when>
		<xsl:when test="$docsubtype = 'profile'">Profile</xsl:when>
		<xsl:when test="$docsubtype = 'profile-with-extension'">Profile with extension</xsl:when>
		<xsl:when test="$docsubtype = 'general'">General</xsl:when>
	</xsl:choose>
</xsl:variable>
```
but in mn xml the element `subdoctype` is using instead of `docsubtype`:
```
<subdoctype>conceptual-model</subdoctype>
```
I don't figure out why `docsubtype` is using... Will change to `subdoctype`.

> let's discuss any differences between the implementation we have and this sample

- identifier
![image](https://user-images.githubusercontent.com/5559926/173775303-43e2a3fa-5991-4785-b5f6-044188e04df6.png)
With title `OGC® DOCUMENT:`:
![image](https://user-images.githubusercontent.com/5559926/173775329-723c37e8-8622-4d09-8883-a07987e2727d.png)

- version
at top:
![image](https://user-images.githubusercontent.com/5559926/173775420-0ec7d1ae-306a-426b-869d-7339f96489ee.png)
at bottom:
![image](https://user-images.githubusercontent.com/5559926/173775447-ac79e28e-aa2b-45ff-be5c-f095c926299c.png)

- url
without title:
![image](https://user-images.githubusercontent.com/5559926/173775510-cd83038e-7a97-497f-8b49-0f7472f64a0f.png)
with title, but renders always when the url is missng:
![image](https://user-images.githubusercontent.com/5559926/173775542-e2256a67-c2bd-451d-b400-5f75dc070469.png)

@ronaldtse would you like to omit this empty title?

**Comment by Intelligent2013** [comment]
Fixed:
- docsubtype added
- empty title `External Identifier...` removed:
![image](https://user-images.githubusercontent.com/5559926/173813458-e74d06ec-194a-40a8-8b74-379615635ef7.png)

**Comment by ronaldtse** [comment]
Thank you! Regarding `subdoctype` vs `docsubtype` let's file a new issue.

**Comment by Intelligent2013** [comment]
> Regarding `subdoctype` vs `docsubtype` let's file a new issue.

I figured it out:
- `docsubtype` is the Metanorma document's attribute in adoc: `:docsubtype: ...`
- `subdoctype` is the Metanorma xml element: `<subdoctype>...</subdoctype>`. And XSLT reads data from it.
