### ISSUE TITLE
(URGENT) Broken `formattedref` in some ISO bibliographic entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#388]
Some bibliographic entries from ISO are not rendering correctly with a broken `formattedref`.

<img width="496" alt="Screenshot 2022-06-15 at 10 02 29 AM" src="https://user-images.githubusercontent.com/11865/173714311-43067010-7f08-4359-9141-acc1345f6dcf.png">

This is clearly a Metanorma issue as the formattedref is broken:

```adoc
* [[[iso9075,ISO/IEC 9075:2003]]], ISO/IEC JTC 1, ISO/IEC 9075:2003 -- Information Technology -- Database Languages - SQL.
```

```xml
  <bibitem id="iso9075" type="standard">
    <formattedref>
      /: ISO/IEC 9075:2003,
      <em>
      ISO/IEC JTC 1, ISO/IEC 9075:2003 — Information Technology — Database
      Languages — SQL.
    </em>
    . ISO, IEC (2003).
  </formattedref>
  <docidentifier type="metanorma-ordinal">
    [3]
  </docidentifier>
  <docidentifier type="ISO">
    ISO/IEC 9075:2003
  </docidentifier>
</bibitem>
```

_Originally posted by @ronaldtse in https://github.com/metanorma/ogc-modspec/issues/3#issuecomment-1155864373_

**Comment by opoudjis** [comment]
First issue is that the reference is not being recognised: it's ISO/IEC 9075-1:2003, but ISO/IEC 9075 returns no hits at all.

The second issue is that relaton-render needs to be more forgiving. What is currently being returned  fed into it, because the citation is not being recognised, is:

````
<bibitem id="iso9075" type="standard">
<title format="text/plain">ISO/IEC JTC 1, ISO/IEC 9075:2003 — Information Technology — Database Languages — SQL.</title>
<docidentifier type="ISO">ISO/IEC 9075:2003</docidentifier><docnumber>9075</docnumber><date type="published"><on>2003</on></date><contributor><role type="publisher"/><organization>
<name>ISO</name>
</organization></contributor><contributor><role type="publisher"/><organization>
<name>IEC</name>
</organization></contributor></bibitem>
````

relaton-render is explicitly looking for an abbreviation of the publisher, and not finding it. It needs to default back to the name if it can't find an abbreviation.
