### ISSUE TITLE
ModSpec implementation refinement: conformance test should accept `requirement` field to link to requirement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#398]
Right now we take this input:
```adoc
[abstract_test]
====
[%metadata]
label:: /conf/core/classes
subject:: <<req_core_classes,/req/core/classes>>
...
====
```

But `subject::` is incorrect. It should have been `requirement::`.

i.e.
```adoc
[abstract_test]
====
[%metadata]
id:: /conf/core/classes
requirement:: /req/core/classes
...
====
```

**Comment by opoudjis** [comment]
`But subject:: is incorrect. It should have been requirement::`.

This is a new requirement, and I don't regard it as legitimate. Not implementing until we have discussed this. If the requirement is not the subject of the test, *then what else is?!* The requirement for descriptive text is already satisfied by formulating the subject as a crossreference.

**Comment by opoudjis** [comment]
Sigh.

I'm implementing this as `target::` on both conformance test and conformance class, and the content of target shall be the bare anchor of the requirement/requirement class, rather than a cross-reference. The presentation as "Requirement class" or "Requirement" will be automated; so will the bidirectional link.

**Comment by opoudjis** [comment]
And this target is not going to added as a new metadata element. We are going to freeze the elements of the requirement submodel, and use "classification" as the extension point for any flavour-specific metadata.

So:

````
[%metadata]
id:: /conf/core/classes
classification:: target:/req/core/classes
````

I will use labels instead of Metanorma anchors as the content of the target, because @ronaldtse said so.

I am therefore breaking all compatibility with Requirement model encoding to date.

**Comment by ronaldtse** [comment]
> If the requirement is not the subject of the test, _then what else is?!_ 

In the context of a "conformance test", "subject" is commonly understood as the thing being tested, i.e. not the requirement, but the thing that the requirement applies to.

> We are going to freeze the elements of the requirement submodel, and use "classification" as the extension point for any flavour-specific metadata.

What exactly is "classification"? Why do we use "classification" to accept key value pairs, when we can just allow free-form attributes instead?

**Comment by ronaldtse** [comment]
> I will not replace "label" with "id". That is a bridge too far, and a frivolous change.

We will use "id" and have "label" as a compatible keyword. It is an important change.

**Comment by opoudjis** [comment]
identifier. We cannot deal in UML with an attribute and an element having the same name.

This is change destabilising the existing tagset, and I am doing this under protest.

**Comment by opoudjis** [comment]
As a result of this acutely painful discussion:

* Links from tests to requirements will be encoded as `classification:: target:{label}`, where `{label}` is the identifier of the requirement from the requirement domain (as opposed to the Metanorma anchor)
* The [%metadata] syntax will be modified, so that any unrecognised definition list term is treated as a classification tag
* The `label` tag for identifiers of the requirement from the requirement domain shall be replaced with `identifier`
* Subject shall not be treated as the link from tests to requirements or vice versa
* Targets shall be rendered as the target class name (Conformance Class, Conformance Test, Requirement Class, Requirement), depending on the class of the requirement being rendered
* Documentation of OGC modspec will need to be updated.
