### ISSUE TITLE
Strange encoding behavior for JSON source block

### ISSUE THREAD

**Issue by jechterhoff** [metanorma/metanorma-ogc#486]
A single (the last) JSON source block in my document is encoded in a rather weird fashion. 

The relevant document source is located at https://github.com/Geonovum/uml2json/blob/main/sections/annex-c.adoc, which contains a link to the JSON file located at https://github.com/Geonovum/uml2json/blob/main/schemas/schema_definitions.json. 

Here is how the JSON is encoded in HTML:

![strange_source_encoding_example](https://user-images.githubusercontent.com/4831647/211252066-b4779c02-e3ee-4ae8-96b1-18dbd87b5342.png)

In Annex B, such code links are encoded correctly. You can find the resulting HTML file at https://github.com/Geonovum/uml2json/blob/main/document.html

What could be causing this strange encoding behavior?

metanorma --version
C:/Users/echte/AppData/Local/Temp/ocrF0FC.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/yaml.rb:21: warning: already initialized constant Rouge::Lexers::YAML::SPECIAL_VALUES
C:/Users/echte/AppData/Local/Temp/ocrF0FC.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/yaml.rb:21: warning: previous definition of SPECIAL_VALUES was here
Metanorma 1.5.4
Metanorma::Cli 1.6.11
Metanorma::Standoc 2.3.6/IsoDoc 2.4.2
Metanorma::ISO 2.3.2
Metanorma::Iec 2.2.2
Metanorma::IEEE 1.0.3
Metanorma::Ietf 3.1.1
Metanorma::Generic 2.3.0
Metanorma::BIPM 2.2.2
Metanorma::CC 2.2.2
Metanorma::Csa 2.2.2
Metanorma::IHO 0.7.2
Metanorma::M3AAWG 2.2.2
Metanorma::UN 0.10.2
Metanorma::Ogc 2.3.2
Metanorma::ITU 2.2.3

**Comment by opoudjis** [comment]
Surprised it's only the last instance, but this has just been solved in https://github.com/metanorma/metanorma-ogc/issues/490

The issue was that if a sourcecode line was entirely encompassed by spans for syntax colouring, and this does happen in JSON (the blank spaces included), then the XML output was formatting the result as pure XML containing XML elements, rather than as mixed text and XML elements; and that was resulting in the XML being indented, with each tag on a separate line:

````
<sourcecode>
  <span>...</span>
  <span>...</span>
  <span>...</span>
</sourcecode>
````

That in turn was resulting in the lines breaking up prematurely (on the first available line break).

**Comment by opoudjis** [comment]
<img width="816" alt="Στιγμιότυπο οθόνης 2023-01-16, 03 33 20" src="https://user-images.githubusercontent.com/1911039/212553615-2717a2c6-4a75-49d3-89a3-77ab7a5cb923.png">
