### ISSUE TITLE
"Contributors" and "Normative References" sections in ER Templates

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#494]
As I understand, "submitters"  and "submitting organizations" were intended for Standards.
In OGC Engineering Reports, prior to metanorma templates there used to be a "contributors" section.
Is this still possible?

On a related note, as I understand "Normative References" are also only intended for Standards, not ERs.
The ER itself not being normative, it does not really make sense to have Normative References. Those should probably also be in bibliography?

Apologies if this is not the right place to report these issues.

cc @gbuehler @ghobona

**Comment by opoudjis** [comment]
As the most recent update to the metanorma templates says (just last week), you can put an arbitrary clause inside the preface, by using the [.preface] attribute on the clause. That lets you use an arbitrary clause, which can include contributors. 

You can always specify a bibliography section to the exclusion of a normative references section, simply by omitting the latter. I will check the ER template as to whether it includes normative references.

**Comment by opoudjis** [comment]
There are References and a Bibliography in the Engineering Reports, and References are indeed normative references. I agree with your reasoning, but I wish @gbuehler or @ghobona to confirm before I remove that section from Engineering Reports (and any other document types that they indicate are non-normative.)

**Comment by ronaldtse** [comment]
Sorry this ticket slipped my notice. We have previously discussed the possibility of structured Contributors with OGC DocTeam in the same way as submitters, but we did not come to a conclusion.

Perhaps we can finally finalize this topic of generalizing all types of contributors (authors, editors, submitters, etc). OGC DocTeam needs to define the types of possible contributors.

> The ER itself not being normative, it does not really make sense to have Normative References. Those should probably also be in bibliography?

This is an interesting topic because even ISO has a hard time defining Normative and Informative according to different contexts:
* normative vs informative content within a document
* normative vs informative documents

The current case in question is an ER (informative document) containing normative references.

My understanding is as follows:
* any document can contain informative and normative content. For example, in an ISO/TS (technical specification) that describes a network protocol, it can contain normative content about the protocol, and therefore also normative references (e.g. to RFCs)
* the decision on adopting a normative or informative document (e.g. OGC standard or OGC ER) is purely on the adoptee
* the adoptee may consider an informative document "normative" in its context. For example, the user may decide that they want to adopt the network protocol mentioned above in an ISO/TS, so for them it is a normative requirement.

The logical conclusion is that an ER should be allowed to contain normative content and also normative references.

**Comment by jerstlouis** [comment]
@ronaldtse 

> The logical conclusion is that an ER should be allowed to contain normative content and also normative references.

OGC ERs come with the foreword:

> This document is not an OGC Standard. This document  ... is not an official position of the OGC membership. .. It is subject to change without notice and may not be referred to as an OGC Standard. Further, any OGC Engineering Report should not be referenced as required or mandatory technology in procurements. 

I understand this as the content of the document being explicitly non-normative, but it may depend on the definition of normative. [Merriam-Webster says](https://www.merriam-webster.com/dictionary/normative):

> 1 of, relating to, or determining norms or standards
2 conforming to or based on norms normative behavior normative judgments
3 prescribing norms

**Comment by jerstlouis** [comment]
@ghobona Perhaps a distinction between _References to normative documents_ in ERs, as opposed to _Normative references_, would make sense.

In particular, the _Normative References_, even in ER templates, often include the preamble:

> The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document.

and it makes no sense to have _requirements_ in an ER.

**Comment by opoudjis** [comment]
This ticket is going on hold until that meeting is held.

**Comment by opoudjis** [comment]
Superseded by #527
