### ISSUE TITLE
XRef to Requirement

### ISSUE THREAD

**Issue by alexrobin** [metanorma/metanorma-ogc#512]
I'm writing an OGC spec and when I reference a requirement with the following syntax: `xref:/req/path/myreq[]`, it gets expanded to this long string: "Clause 7.3.2, Requirement 38: /req/path/myreq".

I was expecting the shorter version "Requirement 38" as described in the [documentation](https://www.metanorma.org/author/topics/document-format/requirements-modspec/#referencing-using-instance-identifiers).

Is this a bug or is there a special style argument I can use to get only the requirement number? ( I tried `id%` and `short%` to no avail).

Thanks

**Comment by opoudjis** [comment]
My apologies for not getting back to you earlier!

The style options to date are:

`[style=id%], [style=basic%], [style=full%], [style=short%], [style=modspec%]`

`style=modspec%` will give you _Requirement 38: `/req/path/myreq`_, which is what Modspec generates inside of tables. I'll add that to documentation, to my surprise I've neglected to.

Right now, there is no way to get just _Requirement 38_ in Modspec.

Now, the strict shadowing of requirements with their relative URIs in cross-references is a requirement of Modspec rendering. 

On the other hand, the inclusion of the clause reference alongside the requirement reference is, strictly speaking, redundant, since requirements number sequentially in a document (outside of annexes). We will canvas internally whether it makes sense to drop that clause reference, so that references would just be _Requirement 38: `/req/path/myreq`_ by default, instead of _Clause 7.3.2,  Requirement 38: `/req/path/myreq`_. We could make the clause prefixing a style option, but to me, it actually makes more sense just to drop the clause reference; but let's find out what makes sense to others (including you!)

@ghobona Does OGC have an opinion on whether cross-references to Modspec requirements in general (from other parts of a document) should be prefixed with "Clause n", indicating the clause they are contained in?

**Comment by opoudjis** [comment]
I've documented the `modspec%` style, but there will be a delay in it getting posted, we are refactoring documentation.

Thank you getting in touch, and please let us know if there is anything else we can do to make authoring easier for you!

**Comment by ronaldtse** [comment]
Thank you @ghobona !
