### ISSUE TITLE
Make use of the "keyword" attribute

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#603]
This proposal is originally by @heidivanparys and was logged at https://github.com/opengeospatial/templates/issues/18

### &#8220;

I would like suggest to add the "keywords" attribute to the templates, and perhaps the "description" keyword as well.

From http://asciidoc.org/userguide.html#X88 :

> The keywords and description attributes set the correspondingly named HTML meta tag contents; the title attribute sets the HTML title tag contents. Their principle use is for SEO (Search Engine Optimisation).

See an example in https://raw.githubusercontent.com/heidivanparys/discussion_paper_dataset/master/dp.adoc .

```
= On the definition of “dataset”
:title: On the definition of “dataset”
:titletext: {Title}
:keywords: dataset,data set,ogcdoc,OGC document
:description: The concept of “dataset” is a key concept in many domains. This document tries to come to a better understanding of it.
```

```
<meta name="description" content="The concept of “dataset” is a key concept in many domains. This document tries to come to a better understanding of it.">
<meta name="keywords" content="dataset,data set,ogcdoc,OGC document">
<title>On the definition of “dataset”</title>
```

### &#8221;

**Comment by heidivanparys** [comment]
The example referred to is an old one, a more updated example, with more metadata, is https://sdfidk.github.io/standarder-for-geodata/:

Source:

- https://github.com/SDFIdk/standarder-for-geodata/blob/347bdb016b79f97c6dbda5b6347de597b13bbe82/docs/docinfo.html#L2-L17
- https://github.com/SDFIdk/standarder-for-geodata/blob/347bdb016b79f97c6dbda5b6347de597b13bbe82/docs/docinfo.html#L82-L103

Result HTML:

- https://github.com/SDFIdk/standarder-for-geodata/blob/b4136d5709e0832bd8104bfc4ae8becb2e175497/index.html#L7-L27
- https://github.com/SDFIdk/standarder-for-geodata/blob/b4136d5709e0832bd8104bfc4ae8becb2e175497/index.html#L92-L113

**Comment by opoudjis** [comment]
The HTML description attribute is at this time populated as the document abstract. (Some recent bugs you found were because the document abstract wasn't being sanitised enough to be inserted into an HTML attribute.) Do you anticipate the description being distinct from the document abstract? The samples you provide do not seem to make that distinction.

The `keywords` are already in most templates, and I'm putting them in the rest:

````
:comment: ### Comma delimited keywords; mandatory
:keywords: ogcdoc, OGC document, Discrete Global Grid System, DGGS, Digital Earth, DGGScore, Spatial Reference System, Global Data Structure, Geographic Information Systems, DE-9IM, standard, specification
````

**Comment by opoudjis** [comment]
I'm happy to insert Dublin Core metadata per your sample if OGC wants that:

````
<link rel="profile" href="http://dublincore.org/documents/2008/08/04/dc-html/" />
<link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
<meta name="DC.creator" lang="{lang}" content="{author}" />
<meta name="DC.date" content="{revdate}" />
<meta name="DC.description" lang="{lang}" content="{description}" />
<meta name="DC.language" content="{lang}" />
<meta name="DC.subject" lang="{lang}" content="{keywords}" />
<meta name="DC.rights" lang="da" content="CC-BY-4.0"/>
<meta name="DC.title" lang="{lang}" content="{doctitle}" />
<link rel="schema.DCTERMS" href="http://purl.org/dc/terms/" />
<link rel="DCTERMS.license" href="https://creativecommons.org/licenses/by/4.0/"/>
````

Of these, 

* the description is also going to be the abstract unless we're told otherwise 
* the date will be the most recent of revision date, date published, date issued (for drafts)
* the creators will be any persons named as authors in the document metadata
* the language defaults as English in Metanorma-OGC, but will be whatever code is set in `:language:` (although that would raise i18n issues.) Note that we use two-letter codes

We make provision for rights/license in our bibliographic model, but we have not to date populated it in Metanorma. (It would be `:license:` if we did.) Is there a universally applicable license in OGC, or would you want that keyed in by users as a document attribute?

**Comment by opoudjis** [comment]
License specified at www.ogc.org/license. Do we use that URL, or specific license?

**Comment by opoudjis** [comment]
@ghobona @ogcscotts I am going away on holiday from 16 Jan until 29 Jan, and I expect we will catch up in early Feb as normal. A reminder that this issue is still pending.

**Comment by ogcscotts** [comment]
@ghobona @opoudjis yes, we can reference the license in the metadata field per the link above.

**Comment by opoudjis** [comment]
Ok, thank you. Hardcoded license, and the rest populated from metadata.
