### ISSUE TITLE
Anchor names not picked up as in asciidoctor -- is this intended?

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#685]
When OGC staff converts standards developed using asciidoctor-pdf to metanorma, a problem we notice (often late in the publication progress, as we just noticed that today for Maps) is that the anchor names  are not being picked up automatically from the section being referenced when not explicitly providing an anchor name.

For example, this often happens in the section 2 - conformance. Instead of seeing _Requirement Class "Core"_, we will see something like _Clause 16_.

Is this behavior difference from asciidoctor intended or a bug that should be fixed?
e.g. see what we had to do to fix this in Maps:

https://github.com/opengeospatial/ogcapi-maps/commit/cf6b388456d5e21661f836952728dc1809df6c53

**Comment by opoudjis** [comment]
The behaviour of Metanorma has from the beginning been to use clause numbers by default for cross-references. In that, we are following ISO, as our model for default standards behaviour

The behaviour you are referring to, of using the clause name instead of a clause number, can be actioned since October 2022: `<<cr_core,style=basic%>>`, and can be set as a document default with the document attribute `:xrefstyle: basic`. That is the same as for native Asciidoc, except that Metanorma's default is `:xrefstyle: short`.
