### ISSUE TITLE
Block issues in latest auto-generated drafts

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#703]
In the latest auto-generated drafts, blocks are not being rendered properly, being all on one line e.g.:

![oneline](https://github.com/user-attachments/assets/346e0bc9-6eb5-4d18-b9ad-d57d868cd0cb)

from https://docs.ogc.org/DRAFTS/20-058.html#_link_from_data_resource

whereas with my local fairly recent metanorma build this does not occur:

![fine](https://github.com/user-attachments/assets/24df9fdb-b0e5-494c-b697-e7ae1c7c746b)

Metanorma 2.0.1
Metanorma::Cli 1.10.1
Metanorma::Ogc 2.5.10

There are several occurences of this throughout [OGC API - Maps](https://github.com/opengeospatial/ogcapi-maps).

not sure what is causing this...

cc. @gbuehler @ghobona @opoudjis

**Comment by opoudjis** [comment]
I suspect it's https://github.com/metanorma/metanorma-utils/releases/tag/v1.9.0, updates not to treat carriage return as whitespace for Chinese/Japanese/Korean text (we're working with Japanese now), and allowing fewer carriage returns in the XML than we used to as a result. Source code was expressly meant not to be impacted by this; I will need to investigate to see what's happened here, but I've got hold of this too late for today's release.

**Comment by opoudjis** [comment]
Ugh.

Sourcecode is preserving carriage return fine. But sourcecode wrapped in examples, as with that example, is now not.

**Comment by opoudjis** [comment]
This is going to be difficult. I have to re-conceive how Nokogiri is processed with regard to the line endings of blocks: they cannot be handled generically in metanorma-utils noko(), but instead need to be handled on a block-by-block basis (as they already are supposed to be), except that nested blocks need to be left alone as single concatenated list elements.

**Comment by opoudjis** [comment]
Yeah, the solution to this is going to have to be:

* Do not do any line-stripping (replacing of carriage return with space, including CJK detection), in noko()
* Do the line stripping in metanorma-standoc in text postprocessing, in the same context as smartquotes_cleanup(xmldoc). 
* Just as smartquotes_cleanup(), the line stripping will ignore any text whose ancestor is passthrough text (and would preserve dumb quotes): carriage returns are left alone in text descended from sourcecode, pre, passthrough, etc, but they are stripped in all other spans of text in Metanorma.

Release has been held up because of fontist issues, so I will fix this tomorrow and re-release.

**Comment by opoudjis** [comment]
Will test entire Metanorma stack and re-release tomorrow, but these fixes address this issue.

**Comment by opoudjis** [comment]
Still need to write test for this new code in standoc, and test remainder of Metanorma.

**Comment by jerstlouis** [comment]
@opoudjis There was also several occurences of this well for the OpenAPI snippets inside of the requirements -- I'm not sure whether it is the exact same scenario or not.

**Comment by opoudjis** [comment]
Realising that, just as with smart quotes, we need to be aware of next line of text within block:

````
<p>
A
<em>B</em>
C
</p>
````

B will be traversed separately from A and C by Nokogiri, since we are isolating text spans; B needs to know that it is followed by C, and whether C is in CJK or not. This needs to be fixed, because right now space is being removed before inline markup.

**Comment by opoudjis** [comment]
After a lot of to-and-fro, I'm satisfied I've addressed this; attaching latest ogc api maps. Will do updated release late tonight, although it is still being held up by https://github.com/fontist/fontist/issues/382

**Comment by ghobona** [comment]
@jerstlouis Thanks for spotting the issue. We will re-check before publishing 20-058.

Cc:  @gbuehler
